### ISSUE TITLE
How do I prevent messing up url() in CSS?

### ISSUE THREAD

**Issue by dougkwilson** [ligershark/WebOptimizer#77]
Pipeline setup:
```csharp
pipeline.AddCssBundle("/bundles/home.css", 
  "node_modules/simple-line-icons/css/simple-line-icons.css",
  "node_modules/html5-device-mockups/dist/device-mockups.css")
  .UseContentRoot();
```

Original (and the desired output) URL in CSS:
```css
@font-face {
  src: url('../fonts/Simple-Line-Icons.eot?v=2.4.0');
}
```
Bundled and Minified CSS:
```css
@font-face {
  src: url('../node_modules/simple-line-icons/fonts/Simple-Line-Icons.eot?v=2.4.0');
}
```
NOTE: It's not just `src: url()`... also happens with `background-image: url(../img/bg.png)` as well.

I have also tried a custom pipeline omitting AdjustRelativePaths() with the same results:
```csharp
pipeline.AddBundle("/bundles/home.css", "text/css; charset=UTF-8",
  "node_modules/simple-line-icons/css/simple-line-icons.css",
  "node_modules/html5-device-mockups/dist/device-mockups.css")
  .EnforceFileExtensions(".css")
  //.AdjustRelativePaths()
  .Concatenate()
  .FingerprintUrls()
  .AddResponseHeader("X-Content-Type-Options", "nosniff")
  .MinifyCss(new CssSettings())
  .UseContentRoot();
```
Any thoughts on what I'm doing wrong?
